name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests with coverage
        run: npm test -- --coverage
        
      - name: Upload Coverage Report
        if: success() # Only upload if tests pass
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov-report
          
      - name: Fail if coverage is low
        run: npm test -- --coverage --watchAll=false
