name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Check out the repository code
      - uses: actions/setup-node@v3 # Set up Node.js
        with:
          node-version: 18
      - run: npm install # Install dependencies
      - run: npm test -- --coverage # Run tests and check coverage
